name: bpmn_dart
publish_to: "none"
version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.19.1
  xml: ^6.5.0
  js: ^0.7.1
  universal_html: ^2.2.4

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.8
