name: modeler
description: An absolute bare-bones web app.
version: 2.0.0
# homepage: https://www.example.com
publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bpmn_dart:
    path: ../../

dev_dependencies:
  build_runner: ^2.4.13
  build_web_compilers: ^4.0.11
  lints: ^5.0.0
